---
- hosts: all
  tasks:
  - name: Download docker-buildx-plugin
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-buildx-plugin-0.10.2-1.el7.x86_64.rpm
      dest: /tmp/docker-buildx-plugin-0.10.2-1.el7.x86_64.rpm
      mode: '0440'